<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;net462;net8.0</TargetFrameworks>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<Title>Balsam.Common.dll</Title>
		<Company>Balsam Research, LLC</Company>
		<Product>Balsam Research Backtesting Framework</Product>
		<Description>Interfaces and enums used for trading related applications across Balsam Research code libraries</Description>
		<Authors>Balsam Research, LLC</Authors>
		<Copyright>Copyright © 2007-2025 Balsam Research, LLC</Copyright>
		<AssemblyVersion>1.0.0.0</AssemblyVersion>
		<FileVersion>1.2.0</FileVersion>
		<PackageVersion>1.2.0</PackageVersion>
		<GeneratePackageOnBuild>False</GeneratePackageOnBuild>
		<PackageId>Balsam.Common</PackageId>
		<PackageOutputPath>$(SolutionDir)\nupkg</PackageOutputPath>
		<PackageProjectUrl>https://www.balsamresearch.com/backtester/</PackageProjectUrl>
		<PackageTags>Balsam Research backtest trading financial markets</PackageTags>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageIcon>Balsam_128px.png</PackageIcon>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<RepositoryUrl>https://github.com/BalsamResearch/balsam-common</RepositoryUrl>
		<ProduceReferenceAssembly>True</ProduceReferenceAssembly>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\Balsam_128px.png">
		  <Pack>True</Pack>
		  <PackagePath>\</PackagePath>
		</None>
		<None Include="README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="License.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

</Project>
